// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/create-qrcode": {
    params: {};
  };
  "/theme": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/card/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/create-qrcode" | "/theme" | "/users" | "/account" | "/card/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/";
  } | {
    id: "login-page";
    page: "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/create-qrcode.tsx": {
    id: "routes/create-qrcode";
    page: "/create-qrcode";
  };
  "routes/theme.tsx": {
    id: "routes/theme";
    page: "/theme";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/public-card.tsx": {
    id: "routes/public-card";
    page: "/card/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "login-page": typeof import("./app/routes/login.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/create-qrcode": typeof import("./app/routes/create-qrcode.tsx");
  "routes/theme": typeof import("./app/routes/theme.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/public-card": typeof import("./app/routes/public-card.tsx");
};